# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
logging:
    level.ROOT: INFO
    level.org.springframework.test.web.servlet.result: DEBUG

spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        # PUBLIC 35.193.165.214
        # PRIVATE 10.25.16.3
        jdbcUrl: jdbc:mysql://35.193.165.214:3306/api_db?useGmtMillisForDatetimes=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: team1
        password: xla1user!
    cloud:
        gcp:
            project-id: gdg-hackathon-1-team
            credentials:
                location: classpath:storage-creater.json

gcp:
    storage:
        bucket: gdg-team1-alibaba-bucket
